// Code generated by ent, DO NOT EDIT.

package viewedmovie

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the viewedmovie type in the database.
	Label = "viewed_movie"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJavdbID holds the string denoting the javdb_id field in the database.
	FieldJavdbID = "javdb_id"
	// FieldViewedAt holds the string denoting the viewed_at field in the database.
	FieldViewedAt = "viewed_at"
	// Table holds the table name of the viewedmovie in the database.
	Table = "viewed_movies"
)

// Columns holds all SQL columns for viewedmovie fields.
var Columns = []string{
	FieldID,
	FieldJavdbID,
	FieldViewedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// JavdbIDValidator is a validator for the "javdb_id" field. It is called by the builders before save.
	JavdbIDValidator func(string) error
	// DefaultViewedAt holds the default value on creation for the "viewed_at" field.
	DefaultViewedAt func() time.Time
)

// OrderOption defines the ordering options for the ViewedMovie queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByJavdbID orders the results by the javdb_id field.
func ByJavdbID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJavdbID, opts...).ToFunc()
}

// ByViewedAt orders the results by the viewed_at field.
func ByViewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewedAt, opts...).ToFunc()
}
