// Code generated by ent, DO NOT EDIT.

package viewedmovie

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ppxb/miyabi/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLTE(FieldID, id))
}

// JavdbID applies equality check predicate on the "javdb_id" field. It's identical to JavdbIDEQ.
func JavdbID(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldJavdbID, v))
}

// ViewedAt applies equality check predicate on the "viewed_at" field. It's identical to ViewedAtEQ.
func ViewedAt(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldViewedAt, v))
}

// JavdbIDEQ applies the EQ predicate on the "javdb_id" field.
func JavdbIDEQ(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldJavdbID, v))
}

// JavdbIDNEQ applies the NEQ predicate on the "javdb_id" field.
func JavdbIDNEQ(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNEQ(FieldJavdbID, v))
}

// JavdbIDIn applies the In predicate on the "javdb_id" field.
func JavdbIDIn(vs ...string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldIn(FieldJavdbID, vs...))
}

// JavdbIDNotIn applies the NotIn predicate on the "javdb_id" field.
func JavdbIDNotIn(vs ...string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNotIn(FieldJavdbID, vs...))
}

// JavdbIDGT applies the GT predicate on the "javdb_id" field.
func JavdbIDGT(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGT(FieldJavdbID, v))
}

// JavdbIDGTE applies the GTE predicate on the "javdb_id" field.
func JavdbIDGTE(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGTE(FieldJavdbID, v))
}

// JavdbIDLT applies the LT predicate on the "javdb_id" field.
func JavdbIDLT(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLT(FieldJavdbID, v))
}

// JavdbIDLTE applies the LTE predicate on the "javdb_id" field.
func JavdbIDLTE(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLTE(FieldJavdbID, v))
}

// JavdbIDContains applies the Contains predicate on the "javdb_id" field.
func JavdbIDContains(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldContains(FieldJavdbID, v))
}

// JavdbIDHasPrefix applies the HasPrefix predicate on the "javdb_id" field.
func JavdbIDHasPrefix(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldHasPrefix(FieldJavdbID, v))
}

// JavdbIDHasSuffix applies the HasSuffix predicate on the "javdb_id" field.
func JavdbIDHasSuffix(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldHasSuffix(FieldJavdbID, v))
}

// JavdbIDEqualFold applies the EqualFold predicate on the "javdb_id" field.
func JavdbIDEqualFold(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEqualFold(FieldJavdbID, v))
}

// JavdbIDContainsFold applies the ContainsFold predicate on the "javdb_id" field.
func JavdbIDContainsFold(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldContainsFold(FieldJavdbID, v))
}

// ViewedAtEQ applies the EQ predicate on the "viewed_at" field.
func ViewedAtEQ(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldViewedAt, v))
}

// ViewedAtNEQ applies the NEQ predicate on the "viewed_at" field.
func ViewedAtNEQ(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNEQ(FieldViewedAt, v))
}

// ViewedAtIn applies the In predicate on the "viewed_at" field.
func ViewedAtIn(vs ...time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldIn(FieldViewedAt, vs...))
}

// ViewedAtNotIn applies the NotIn predicate on the "viewed_at" field.
func ViewedAtNotIn(vs ...time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNotIn(FieldViewedAt, vs...))
}

// ViewedAtGT applies the GT predicate on the "viewed_at" field.
func ViewedAtGT(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGT(FieldViewedAt, v))
}

// ViewedAtGTE applies the GTE predicate on the "viewed_at" field.
func ViewedAtGTE(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGTE(FieldViewedAt, v))
}

// ViewedAtLT applies the LT predicate on the "viewed_at" field.
func ViewedAtLT(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLT(FieldViewedAt, v))
}

// ViewedAtLTE applies the LTE predicate on the "viewed_at" field.
func ViewedAtLTE(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLTE(FieldViewedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ViewedMovie) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ViewedMovie) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ViewedMovie) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.NotPredicates(p))
}
