// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/ent/predicate"
	"github.com/ppxb/miyabi/internal/ent/viewedmovie"
)

// ViewedMovieDelete is the builder for deleting a ViewedMovie entity.
type ViewedMovieDelete struct {
	config
	hooks    []Hook
	mutation *ViewedMovieMutation
}

// Where appends a list predicates to the ViewedMovieDelete builder.
func (_d *ViewedMovieDelete) Where(ps ...predicate.ViewedMovie) *ViewedMovieDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ViewedMovieDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ViewedMovieDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ViewedMovieDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(viewedmovie.Table, sqlgraph.NewFieldSpec(viewedmovie.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ViewedMovieDeleteOne is the builder for deleting a single ViewedMovie entity.
type ViewedMovieDeleteOne struct {
	_d *ViewedMovieDelete
}

// Where appends a list predicates to the ViewedMovieDelete builder.
func (_d *ViewedMovieDeleteOne) Where(ps ...predicate.ViewedMovie) *ViewedMovieDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ViewedMovieDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{viewedmovie.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ViewedMovieDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
