// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/ent/predicate"
	"github.com/ppxb/miyabi/internal/ent/viewedmovie"
)

// ViewedMovieUpdate is the builder for updating ViewedMovie entities.
type ViewedMovieUpdate struct {
	config
	hooks    []Hook
	mutation *ViewedMovieMutation
}

// Where appends a list predicates to the ViewedMovieUpdate builder.
func (_u *ViewedMovieUpdate) Where(ps ...predicate.ViewedMovie) *ViewedMovieUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJavdbID sets the "javdb_id" field.
func (_u *ViewedMovieUpdate) SetJavdbID(v string) *ViewedMovieUpdate {
	_u.mutation.SetJavdbID(v)
	return _u
}

// SetNillableJavdbID sets the "javdb_id" field if the given value is not nil.
func (_u *ViewedMovieUpdate) SetNillableJavdbID(v *string) *ViewedMovieUpdate {
	if v != nil {
		_u.SetJavdbID(*v)
	}
	return _u
}

// SetViewedAt sets the "viewed_at" field.
func (_u *ViewedMovieUpdate) SetViewedAt(v time.Time) *ViewedMovieUpdate {
	_u.mutation.SetViewedAt(v)
	return _u
}

// SetNillableViewedAt sets the "viewed_at" field if the given value is not nil.
func (_u *ViewedMovieUpdate) SetNillableViewedAt(v *time.Time) *ViewedMovieUpdate {
	if v != nil {
		_u.SetViewedAt(*v)
	}
	return _u
}

// Mutation returns the ViewedMovieMutation object of the builder.
func (_u *ViewedMovieUpdate) Mutation() *ViewedMovieMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ViewedMovieUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ViewedMovieUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ViewedMovieUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ViewedMovieUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ViewedMovieUpdate) check() error {
	if v, ok := _u.mutation.JavdbID(); ok {
		if err := viewedmovie.JavdbIDValidator(v); err != nil {
			return &ValidationError{Name: "javdb_id", err: fmt.Errorf(`ent: validator failed for field "ViewedMovie.javdb_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ViewedMovieUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(viewedmovie.Table, viewedmovie.Columns, sqlgraph.NewFieldSpec(viewedmovie.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JavdbID(); ok {
		_spec.SetField(viewedmovie.FieldJavdbID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ViewedAt(); ok {
		_spec.SetField(viewedmovie.FieldViewedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{viewedmovie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ViewedMovieUpdateOne is the builder for updating a single ViewedMovie entity.
type ViewedMovieUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ViewedMovieMutation
}

// SetJavdbID sets the "javdb_id" field.
func (_u *ViewedMovieUpdateOne) SetJavdbID(v string) *ViewedMovieUpdateOne {
	_u.mutation.SetJavdbID(v)
	return _u
}

// SetNillableJavdbID sets the "javdb_id" field if the given value is not nil.
func (_u *ViewedMovieUpdateOne) SetNillableJavdbID(v *string) *ViewedMovieUpdateOne {
	if v != nil {
		_u.SetJavdbID(*v)
	}
	return _u
}

// SetViewedAt sets the "viewed_at" field.
func (_u *ViewedMovieUpdateOne) SetViewedAt(v time.Time) *ViewedMovieUpdateOne {
	_u.mutation.SetViewedAt(v)
	return _u
}

// SetNillableViewedAt sets the "viewed_at" field if the given value is not nil.
func (_u *ViewedMovieUpdateOne) SetNillableViewedAt(v *time.Time) *ViewedMovieUpdateOne {
	if v != nil {
		_u.SetViewedAt(*v)
	}
	return _u
}

// Mutation returns the ViewedMovieMutation object of the builder.
func (_u *ViewedMovieUpdateOne) Mutation() *ViewedMovieMutation {
	return _u.mutation
}

// Where appends a list predicates to the ViewedMovieUpdate builder.
func (_u *ViewedMovieUpdateOne) Where(ps ...predicate.ViewedMovie) *ViewedMovieUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ViewedMovieUpdateOne) Select(field string, fields ...string) *ViewedMovieUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ViewedMovie entity.
func (_u *ViewedMovieUpdateOne) Save(ctx context.Context) (*ViewedMovie, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ViewedMovieUpdateOne) SaveX(ctx context.Context) *ViewedMovie {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ViewedMovieUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ViewedMovieUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ViewedMovieUpdateOne) check() error {
	if v, ok := _u.mutation.JavdbID(); ok {
		if err := viewedmovie.JavdbIDValidator(v); err != nil {
			return &ValidationError{Name: "javdb_id", err: fmt.Errorf(`ent: validator failed for field "ViewedMovie.javdb_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ViewedMovieUpdateOne) sqlSave(ctx context.Context) (_node *ViewedMovie, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(viewedmovie.Table, viewedmovie.Columns, sqlgraph.NewFieldSpec(viewedmovie.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ViewedMovie.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, viewedmovie.FieldID)
		for _, f := range fields {
			if !viewedmovie.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != viewedmovie.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JavdbID(); ok {
		_spec.SetField(viewedmovie.FieldJavdbID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ViewedAt(); ok {
		_spec.SetField(viewedmovie.FieldViewedAt, field.TypeTime, value)
	}
	_node = &ViewedMovie{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{viewedmovie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
