// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/ent/viewedmovie"
)

// ViewedMovieCreate is the builder for creating a ViewedMovie entity.
type ViewedMovieCreate struct {
	config
	mutation *ViewedMovieMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetJavdbID sets the "javdb_id" field.
func (_c *ViewedMovieCreate) SetJavdbID(v string) *ViewedMovieCreate {
	_c.mutation.SetJavdbID(v)
	return _c
}

// SetViewedAt sets the "viewed_at" field.
func (_c *ViewedMovieCreate) SetViewedAt(v time.Time) *ViewedMovieCreate {
	_c.mutation.SetViewedAt(v)
	return _c
}

// SetNillableViewedAt sets the "viewed_at" field if the given value is not nil.
func (_c *ViewedMovieCreate) SetNillableViewedAt(v *time.Time) *ViewedMovieCreate {
	if v != nil {
		_c.SetViewedAt(*v)
	}
	return _c
}

// Mutation returns the ViewedMovieMutation object of the builder.
func (_c *ViewedMovieCreate) Mutation() *ViewedMovieMutation {
	return _c.mutation
}

// Save creates the ViewedMovie in the database.
func (_c *ViewedMovieCreate) Save(ctx context.Context) (*ViewedMovie, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ViewedMovieCreate) SaveX(ctx context.Context) *ViewedMovie {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ViewedMovieCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ViewedMovieCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ViewedMovieCreate) defaults() {
	if _, ok := _c.mutation.ViewedAt(); !ok {
		v := viewedmovie.DefaultViewedAt()
		_c.mutation.SetViewedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ViewedMovieCreate) check() error {
	if _, ok := _c.mutation.JavdbID(); !ok {
		return &ValidationError{Name: "javdb_id", err: errors.New(`ent: missing required field "ViewedMovie.javdb_id"`)}
	}
	if v, ok := _c.mutation.JavdbID(); ok {
		if err := viewedmovie.JavdbIDValidator(v); err != nil {
			return &ValidationError{Name: "javdb_id", err: fmt.Errorf(`ent: validator failed for field "ViewedMovie.javdb_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ViewedAt(); !ok {
		return &ValidationError{Name: "viewed_at", err: errors.New(`ent: missing required field "ViewedMovie.viewed_at"`)}
	}
	return nil
}

func (_c *ViewedMovieCreate) sqlSave(ctx context.Context) (*ViewedMovie, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ViewedMovieCreate) createSpec() (*ViewedMovie, *sqlgraph.CreateSpec) {
	var (
		_node = &ViewedMovie{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(viewedmovie.Table, sqlgraph.NewFieldSpec(viewedmovie.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.JavdbID(); ok {
		_spec.SetField(viewedmovie.FieldJavdbID, field.TypeString, value)
		_node.JavdbID = value
	}
	if value, ok := _c.mutation.ViewedAt(); ok {
		_spec.SetField(viewedmovie.FieldViewedAt, field.TypeTime, value)
		_node.ViewedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ViewedMovie.Create().
//		SetJavdbID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ViewedMovieUpsert) {
//			SetJavdbID(v+v).
//		}).
//		Exec(ctx)
func (_c *ViewedMovieCreate) OnConflict(opts ...sql.ConflictOption) *ViewedMovieUpsertOne {
	_c.conflict = opts
	return &ViewedMovieUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ViewedMovie.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ViewedMovieCreate) OnConflictColumns(columns ...string) *ViewedMovieUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ViewedMovieUpsertOne{
		create: _c,
	}
}

type (
	// ViewedMovieUpsertOne is the builder for "upsert"-ing
	//  one ViewedMovie node.
	ViewedMovieUpsertOne struct {
		create *ViewedMovieCreate
	}

	// ViewedMovieUpsert is the "OnConflict" setter.
	ViewedMovieUpsert struct {
		*sql.UpdateSet
	}
)

// SetJavdbID sets the "javdb_id" field.
func (u *ViewedMovieUpsert) SetJavdbID(v string) *ViewedMovieUpsert {
	u.Set(viewedmovie.FieldJavdbID, v)
	return u
}

// UpdateJavdbID sets the "javdb_id" field to the value that was provided on create.
func (u *ViewedMovieUpsert) UpdateJavdbID() *ViewedMovieUpsert {
	u.SetExcluded(viewedmovie.FieldJavdbID)
	return u
}

// SetViewedAt sets the "viewed_at" field.
func (u *ViewedMovieUpsert) SetViewedAt(v time.Time) *ViewedMovieUpsert {
	u.Set(viewedmovie.FieldViewedAt, v)
	return u
}

// UpdateViewedAt sets the "viewed_at" field to the value that was provided on create.
func (u *ViewedMovieUpsert) UpdateViewedAt() *ViewedMovieUpsert {
	u.SetExcluded(viewedmovie.FieldViewedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ViewedMovie.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ViewedMovieUpsertOne) UpdateNewValues() *ViewedMovieUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ViewedMovie.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ViewedMovieUpsertOne) Ignore() *ViewedMovieUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ViewedMovieUpsertOne) DoNothing() *ViewedMovieUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ViewedMovieCreate.OnConflict
// documentation for more info.
func (u *ViewedMovieUpsertOne) Update(set func(*ViewedMovieUpsert)) *ViewedMovieUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ViewedMovieUpsert{UpdateSet: update})
	}))
	return u
}

// SetJavdbID sets the "javdb_id" field.
func (u *ViewedMovieUpsertOne) SetJavdbID(v string) *ViewedMovieUpsertOne {
	return u.Update(func(s *ViewedMovieUpsert) {
		s.SetJavdbID(v)
	})
}

// UpdateJavdbID sets the "javdb_id" field to the value that was provided on create.
func (u *ViewedMovieUpsertOne) UpdateJavdbID() *ViewedMovieUpsertOne {
	return u.Update(func(s *ViewedMovieUpsert) {
		s.UpdateJavdbID()
	})
}

// SetViewedAt sets the "viewed_at" field.
func (u *ViewedMovieUpsertOne) SetViewedAt(v time.Time) *ViewedMovieUpsertOne {
	return u.Update(func(s *ViewedMovieUpsert) {
		s.SetViewedAt(v)
	})
}

// UpdateViewedAt sets the "viewed_at" field to the value that was provided on create.
func (u *ViewedMovieUpsertOne) UpdateViewedAt() *ViewedMovieUpsertOne {
	return u.Update(func(s *ViewedMovieUpsert) {
		s.UpdateViewedAt()
	})
}

// Exec executes the query.
func (u *ViewedMovieUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ViewedMovieCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ViewedMovieUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ViewedMovieUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ViewedMovieUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ViewedMovieCreateBulk is the builder for creating many ViewedMovie entities in bulk.
type ViewedMovieCreateBulk struct {
	config
	err      error
	builders []*ViewedMovieCreate
	conflict []sql.ConflictOption
}

// Save creates the ViewedMovie entities in the database.
func (_c *ViewedMovieCreateBulk) Save(ctx context.Context) ([]*ViewedMovie, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ViewedMovie, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ViewedMovieMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ViewedMovieCreateBulk) SaveX(ctx context.Context) []*ViewedMovie {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ViewedMovieCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ViewedMovieCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ViewedMovie.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ViewedMovieUpsert) {
//			SetJavdbID(v+v).
//		}).
//		Exec(ctx)
func (_c *ViewedMovieCreateBulk) OnConflict(opts ...sql.ConflictOption) *ViewedMovieUpsertBulk {
	_c.conflict = opts
	return &ViewedMovieUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ViewedMovie.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ViewedMovieCreateBulk) OnConflictColumns(columns ...string) *ViewedMovieUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ViewedMovieUpsertBulk{
		create: _c,
	}
}

// ViewedMovieUpsertBulk is the builder for "upsert"-ing
// a bulk of ViewedMovie nodes.
type ViewedMovieUpsertBulk struct {
	create *ViewedMovieCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ViewedMovie.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ViewedMovieUpsertBulk) UpdateNewValues() *ViewedMovieUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ViewedMovie.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ViewedMovieUpsertBulk) Ignore() *ViewedMovieUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ViewedMovieUpsertBulk) DoNothing() *ViewedMovieUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ViewedMovieCreateBulk.OnConflict
// documentation for more info.
func (u *ViewedMovieUpsertBulk) Update(set func(*ViewedMovieUpsert)) *ViewedMovieUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ViewedMovieUpsert{UpdateSet: update})
	}))
	return u
}

// SetJavdbID sets the "javdb_id" field.
func (u *ViewedMovieUpsertBulk) SetJavdbID(v string) *ViewedMovieUpsertBulk {
	return u.Update(func(s *ViewedMovieUpsert) {
		s.SetJavdbID(v)
	})
}

// UpdateJavdbID sets the "javdb_id" field to the value that was provided on create.
func (u *ViewedMovieUpsertBulk) UpdateJavdbID() *ViewedMovieUpsertBulk {
	return u.Update(func(s *ViewedMovieUpsert) {
		s.UpdateJavdbID()
	})
}

// SetViewedAt sets the "viewed_at" field.
func (u *ViewedMovieUpsertBulk) SetViewedAt(v time.Time) *ViewedMovieUpsertBulk {
	return u.Update(func(s *ViewedMovieUpsert) {
		s.SetViewedAt(v)
	})
}

// UpdateViewedAt sets the "viewed_at" field to the value that was provided on create.
func (u *ViewedMovieUpsertBulk) UpdateViewedAt() *ViewedMovieUpsertBulk {
	return u.Update(func(s *ViewedMovieUpsert) {
		s.UpdateViewedAt()
	})
}

// Exec executes the query.
func (u *ViewedMovieUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ViewedMovieCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ViewedMovieCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ViewedMovieUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
